// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUDp2N7IfB4U4jpMhW3961I4ntgZIQiJY',
    appId: '1:297808053371:web:e4a5bb9c04e6a3a914cede',
    messagingSenderId: '297808053371',
    projectId: 'vitrox-furguardian',
    authDomain: 'vitrox-furguardian.firebaseapp.com',
    storageBucket: 'vitrox-furguardian.appspot.com',
    measurementId: 'G-EDJ3WDDDS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd3adoQb2pBtNBMrl4vTmTtDjYQquLh4M',
    appId: '1:297808053371:android:ce1368a5bfa808b114cede',
    messagingSenderId: '297808053371',
    projectId: 'vitrox-furguardian',
    storageBucket: 'vitrox-furguardian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZEgNOYQSr8_4yhU9LEwdBtY7pcGmaOT8',
    appId: '1:297808053371:ios:5ecd3c48337f778614cede',
    messagingSenderId: '297808053371',
    projectId: 'vitrox-furguardian',
    storageBucket: 'vitrox-furguardian.appspot.com',
    iosBundleId: 'com.example.vitroxfurguardians',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZEgNOYQSr8_4yhU9LEwdBtY7pcGmaOT8',
    appId: '1:297808053371:ios:5ecd3c48337f778614cede',
    messagingSenderId: '297808053371',
    projectId: 'vitrox-furguardian',
    storageBucket: 'vitrox-furguardian.appspot.com',
    iosBundleId: 'com.example.vitroxfurguardians',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUDp2N7IfB4U4jpMhW3961I4ntgZIQiJY',
    appId: '1:297808053371:web:f3539829c071961114cede',
    messagingSenderId: '297808053371',
    projectId: 'vitrox-furguardian',
    authDomain: 'vitrox-furguardian.firebaseapp.com',
    storageBucket: 'vitrox-furguardian.appspot.com',
    measurementId: 'G-WMBEP7DXTG',
  );
}
